export const hardcodedArtists = ["lana del rey"]

interface Artist {
    name: string;
    albums: Album[];
}

interface Album {
    albumName: string;
    albumId: number;
    tracks: Track[];
}

interface Track {
    trackName: string;
    lyrics: string;
}

export const hardcodedArtistContent: Artist[] = [
    {
        name: "lana del rey",
        albums: [
            {
                albumName: "Honeymoon",
                albumId: 1,
                tracks: [
                    { trackName: "Honeymoon", lyrics: "We both know that it\'s not fashionable to love me\nBut you don\'t go \'cause truly there\'s nobody for you but me\nWe could cruise to the blues\nWilshire Boulevard if we choose\nOr whatever you want to do\nWe make the rules\nOur honeymoon\nOur honeymoon\nOur honeymoon\nSay you want me too\nSay you want me too\nDark blue\nDark blue\nWe both know the history of violence that surrounds you\nBut I\'m not scared, there\'s nothing to lose now that I\'ve found you\nAnd we could cruise to the news\nPico Boulevard in your used\nLittle bullet car if we choose\nMr. born to lose\nOur honeymoon\nOur honeymoon\nOur honeymoon\nSay you want me too\nSay you want me too\nDark blue\nDark blue\nThere are violets in your eyes\nThere are guns that blaze around you\nThere are roses in between my thighs\nAnd a fire that surrounds you\nIt\'s no wonder every man in town\nHad neither fought nor found you\nEverything you do is elusive\nTo even your honey dew" },
                    { trackName: "Music To Watch The Boys To", lyrics: "Putting on my music while I\'m watching the boys\n(So I do what you want)\nSinging soft grunge just to soak up the noise\n(With ribbons in knots)\nPlay \'em like guitars, only one of my toys\n(\'Cause I like you a lot)\nNo holds barred, I was sent to destroy, yeah\nPink flamingos\nAlways fascinated me\nI know what only the girls know\nHoes with lies akin to me\nI, I see you\'re going\nSo I play my music, watch you leave\nPutting on my music while I\'m watching the boys\n(So I do what you want)\nSinging soft grunge just to soak up the noise\n(With ribbons in knots)\nPlay \'em like guitars, only one of my toys\n(\'Cause I like you a lot)\nNo holds barred, I was sent to destroy, yeah\nVelveteen and living single\nIt never felt that right to me\nI know what only the girls know\nLies can buy eternity\nI, I see you leaving\nSo I push record and watch you leave\nPutting on my music while I\'m watching the boys\n(So I do what you want)\nSinging soft grunge just to soak up the noise\n(With ribbons in knots)\nPlay \'em like guitars, only one of my toys\n(\'Cause I like you a lot)\nNo holds barred, I was sent to destroy, yeah\nI live to love you\nAnd I love to love you\nAnd I live to love you, boy\nI live to love you\nAnd I love to love you\nAnd I live to love you, boy\nNothing gold can stay\nLike love or lemonade\nOr sun or summer days\nIt\'s all a game to me anyway\nPutting on my music while I\'m watching the boys\n(So I do what you want)\nSinging soft grunge just to soak up the noise\n(With ribbons in knots)\nPlay \'em like guitars, only one of my toys\n(\'Cause I like you a lot)\nNo holds barred, I was sent to destroy, yeah\nPutting on my music while I\'m watching the boys\nPutting on my music while I\'m watching the boys" },

                ]
            },
            {
                albumName: "Born To Die",
                albumId: 2,
                tracks: [
                    { trackName: "TODO", lyrics: "TOFO BTD 1" },
                    { trackName: "TODO", lyrics: "TODO BTD 2" },
                    { trackName: "TODO", lyrics: "TODO BTD 3" },
                    { trackName: "TODO", lyrics: "TODO BTD 4" },
                    { trackName: "TODO", lyrics: "TODO BTD 5" },
                ]
            },
            {
                albumName: "Ultraviolence",
                albumId: 3,
                tracks: [
                    { trackName: "Cruel World", lyrics: "Share my body and my mind with you\nThat\'s all over now\nDid what I had to do\n\'Cause you\'re so far past me now\nShare my body and my life with you\nThat\'s way over now\nThere\'s not anymore I can do\nYou\'re so famous now\nGot your Bible, got your gun\nAnd you like to party and have fun\nAnd I like my candy and your women\nI\'m finally happy now that you\'re gone\nGot my little red party dress on\nEverybody knows that I\'m the best\nI\'m crazy, yeah yeah\nGet a little bit of Bourbon in ya\nGet a little bit suburban\nAnd go crazy, yeah yeah\nBecause you\'re young, you\'re wild, you\'re free\nYou\'re dancing circles around me\nYou\'re fucking crazy\nOh oh, oh oh, you\'re crazy for me\nI shared my body and my mind with you\nThat\'s all over now\nI did what I had to do\nI found another, anyhow\nShared my body and my mind with you\nThat\'s all over now\nI did what I had to do\nI could see you leaving now\nI got your Bible and your gun\nAnd you love to party and have fun\nAnd I love your women and all of your heroin\nAnd I\'m so happy now that you\'re gone\nGot my little red party dress on\nEverybody knows that I\'m a mess\nI\'m crazy, yeah yeah\nGet a little bit of Bourbon in ya\nGet a little bit suburban\nAnd go crazy, yeah yeah\nBecause you\'re young, you\'re wild, you\'re free\nYou\'re dancing circles around me\nYou\'re fucking crazy\nOh oh oh oh, oh oh oh oh, you\'re crazy for me\nGot your Bible and your gun\nYou like your women and you like fun\nI like my candy and your heroin\nAnd I\'m so happy, so happy now you\'re gone\nGot my little red party dress on\nEverybody knows that I\'m the best\nI\'m crazy, yeah yeah\nGet a little bit of Bourbon in \'ya\nGet a little bit suburban\nAnd go crazy, yeah yeah\nBecause you\'re young, you\'re wild, you\'re free\nYou\'re dancing circles around me\nYou\'re fucking crazy\nOh oh oh, oh oh oh, you\'re crazy for me\nOh oh, oh, you\'re crazy for me" },
                    { trackName: "Shades Of Cool", lyrics: "My baby lives in shades of blue\nBlue eyes and jazz and attitude\nHe lives in California too\nHe drives a Chevy Malibu\nAnd when he calls, he calls for me and not for you\nHe lives for love, he loves his drugs, he loves his baby too\nBut I can\'t fix him, can\'t make him better\nAnd I can\'t do nothing about his strange weather\nBut you are unfixable\nI can\'t break through your world\n\'Cause you live in shades of cool\nYour heart is unbreakable\nMy baby lives in shades of cool\nCold heart and hands and aptitude\nHe lives for love, for women too\nI\'m one of many, Bonnie\'s blue\nAnd when he calls, he calls for me and not for you\nHe prays for love, he prays for peace, and maybe someone new\nBut I can\'t help him, can\'t make him better\nAnd I can\'t do nothing about his strange weather\n\'Cause you are unfixable\nI can\'t break through your world\n\'Cause you live in shades of cool\nYour heart is unbreakable\nYour hot, hot weather in the summer\nHigh, high, neglectful lover\nHot, hot weather in the summer\nHigh, neglectful lover\nYou\'re crumbling, sadly\nYou\'re sadly, crumbling\nYou are unfixable\nI can\'t break through your world\n\'Cause you live in shades of cool\nYour heart is unbreakable" },
                    { trackName: "Brooklyn Baby", lyrics: "They say I\'m too young to love you\nI don\'t know what I need\nThey think I don\'t understand\nThe freedom land of the seventies\nI think I\'m too cool to know ya\nYou say I\'m like the ice, I freeze\nI\'m churnin\' out novels like\nBeat poetry on Amphetamines\nI say\nI say\nWell, my boyfriend\'s in a band\nHe plays guitar while I sing Lou Reed\nI\'ve got feathers in my hair\nI get down to Beat poetry\nAnd my jazz collection\'s rare\nI can play most anything\nI\'m a Brooklyn baby\nI\'m a Brooklyn baby\nThey say I\'m too young to love you\nThey say I\'m too dumb to see\nThey judge me like a picture book\nBy the colors, like they forgot to read\nI think we\'re like fire and water\nI think we\'re like the wind and sea\nYou\'re burnin\' up, I\'m coolin\' down\nYou\'re up, I\'m down\nYou\'re blind, I see\nBut I\'m free, ooh-ooh\nI\'m free\nWell, my boyfriend\'s in a band\nHe plays guitar while I sing Lou Reed\nI\'ve got feathers in my hair\nI get down to Beat poetry\nAnd my jazz collection\'s rare\nI can play most anything\nI\'m a Brooklyn baby\nI\'m a Brooklyn baby\nI\'m talking about my generation\nTalking about that newer nation\nAnd if you don\'t like it, you can beat it\nBeat it, baby\nYou never liked the way I said it\nIf you don\'t get it, then forget it\n\'Cause I don\'t have to fuckin\' explain it\nAnd my boyfriend\'s in a band\nHe plays guitar while I sing Lou Reed\nI\'ve got feathers in my hair\nI get high on hydroponic weed\nAnd my jazz collection\'s rare\nI get down to Beat poetry\nI\'m a Brooklyn baby\nI\'m a Brooklyn baby\nYeah, my boyfriend\'s pretty cool\nBut he\'s not as cool as me\n\'Cause I\'m a Brooklyn baby\nI\'m a Brooklyn baby" },
                    { trackName: "West Coast", lyrics: "I can see my baby swingin\'\nOoh baby baby bae, I love you\nI can see my baby swingin\'\nOoh baby baby bae, I love you\nI can see my baby swingin\'\nOoh baby baby bae, I love you\nI can see my baby swingin\'\nDown on the West Coast they got a sayin\'\n\"If you\'re not drinkin\' then you\'re not playin\'\"\nBut you\'ve got the music, you\'ve got the music\nIn you, don\'t you?\nDown on the West Coast, I get this feeling like\nIt all could happen, that\'s why I\'m leaving\nYou for the moment, you for the moment\nBoy blue, yeah you\nI can see my baby swingin\'\nI can see my baby swingin\'\nDown on the West Coast, they got their icons\nTheir silver starlets, their Queens of Saigons\nAnd you\'ve got the music, you\'ve got the music\nIn you, don\'t you?\nDown on the West Coast, they love their movies\nTheir golden gods and rock and roll groupies\nAnd you\'ve got the music, you\'ve got the music\nIn you, don\'t you?\nI can see my baby swingin\'\nI can see my baby swingin\'\nYou push it hard, I pull away, I\'m feeling hotter than fire\nI guess that no one ever really made me feel that much higher\nTe deseo, carino, boy, it\'s you I desire\nYour love, your love\n" },
                    { trackName: "Sad Girl", lyrics: "Being a mistress on the side\nIt might not appeal to fools like you\nCreeping around on the side\nMight not be something you would do\nBut you haven\'t seen my man (man)\nYou haven\'t seen my man (man, man)\nYou haven\'t seen my man (man)\nYou haven\'t seen him (woah-oh)\nHe\'s got the fire\nAnd he walks with it\nHe\'s got the fire\nAnd he talks with it\nHis Bonnie on the side, Bonnie on the side\nMakes me a sad, sad girl\nHis money on the side, money on the side\nMakes me a sad, sad girl\nI\'m a sad girl\nI\'m a sad girl\nI\'m a sad girl\nI\'m a sad girl\nI\'m a bad girl\nI\'m a bad girl\nBeing a bad bitch on the side\nMight not appeal to fools like you\nCreeping around while he gets high\nIt might not be something you would do, but\nYou haven\'t seen my man (man)\nYou haven\'t seen my man (man, man)\nYou haven\'t seen my man (man)\nYou haven\'t seen him (woah-oh)\nHe\'s got the fire\nAnd he walks with it\nHe\'s got the fire\nAnd he talks with it\nHis Bonnie on the side, Bonnie on the side\nMakes me a sad, sad girl\nHis money on the side, money on the side\nMakes me a sad, sad girl\nI\'m a sad girl\nI\'m a sad girl\nI\'m a sad girl\nI\'m a sad girl\nI\'m a bad girl\nI\'m a bad girl\nWatch what you say to me\nCareful who you\'re talking to\nWatch what you say to me\nCareful who you\'re talking to\nI\'m on fire, baby\nI\'m on fire\nHe\'s got the fire\nAnd he walks with it\nHe\'s got the fire\nAnd he talks with it\nHis Bonnie on the side, Bonnie on the side\nMakes me a sad, sad girl\nHis money on the side, money on the side\nMakes me a sad, sad girl" },
                    { trackName: "Pretty When You Cry", lyrics: "All the pretty stars shine for you, my love\nAm I the girl that you dream of?\nAll those little times you said that I\'m your girl\nYou make me feel like your whole world\nI\'ll wait for you, babe, that\'s all I do, babe\nDon\'t come through, babe, you never do\nBecause I\'m pretty when I cry\nI\'m pretty when I cry\nI\'m pretty when I cry\nI\'m pretty when I cry\nAll those special times I spent with you, my love\nThey don\'t mean shit compared to all your drugs\nBut I don\'t really mind, I\'ve got much more than that\nLike my memories, I don\'t need that\nI\'ll wait for you, babe, you don\'t come through, babe\nYou never do, babe, that\'s just what you do\nBecause I\'m pretty when I cry\nI\'m pretty when I cry\nI\'m pretty when I cry\nI\'m pretty when I cry\nDon\'t say you need me when\nYou leave and you leave again\nI\'m stronger than all my men\nExcept for you\nDon\'t say you need me if\nYou live last, you\'re leaving\nI can\'t do it, I can\'t do it\nBut you do it best\n\'Cause I\'m pretty when I cry, I\'m pretty when I cry\nPretty when I cry, I\'m pretty when I cry\nPretty when I cry, I\'m pretty when I cry\nI\'m pretty when I cry\nI\'m pretty when I cry" },
                    { trackName: "Money Power Glory", lyrics: "You say that you wanna go\nTo a land that\'s far away\nHow are we supposed to get there\nWith the way that we\'re living today?\nYou talk lots about God\nFreedom comes from the call\nBut that\'s not what this bitch wants\nNot what I want at all\nI want money, power and glory\nI want money and all your power, all your glory\nHallelujah, I wanna take you for all that you got\nHallelujah, I\'m gonna take them for all that they got\nThe sun also rises on those who fail to call\nMy life, it comprises of losses and wins and fails and falls\nI can do it if you really, really like that\nI know what you really want, b-baby\nI can do it if you think you like that\nYou should run, boy, run\nI want money, power and glory\nI want money and all your power, all your glory\nHallelujah, I wanna take you for all that you got\nHallelujah, I\'m gonna take them for all that they got\nDope and diamonds\nDope and diamonds\nDiamonds\nDope and diamonds\nDope and diamonds\nThat\'s all I am\nDope and diamonds\nDope and diamonds\nDiamonds\nDope and diamonds\nDope and diamonds\nDiamonds\nI want money, power and glory\nI want money and all your power, all your glory\nHallelujah, I wanna take you for all that you got\nHallelujah, I\'m gonna take them for all that they got" },
                    { trackName: "Fucked My Way Up To The Top", lyrics: "Life is awesome, I confess\nWhat I do, I do best\nYou got nothing, I got tested\nAnd I\'m best, yes\nLay me down tonight in my linen and curls\nLay me down tonight, Riviera girls\nI fucked my way up to the top\nThis is my show\nI fucked my way up to the top\nGo, baby, go (go, go, go, go, go)\nThis is my show (go, go, go, go, go)\nThis is my show\nI\'m a dragon, you\'re a whore\nDon\'t even know what you\'re good for\nMimicking me is a fucking bore to me\nBut babe\nLay me down tonight in my diamonds and pearls\nTell me songs at night about your favorite girl\nI fucked my way up to the top\nThis is my show\nI fucked my way up to the top\nGo, baby, go (go, go, go, go, go)\nThis is my show (go, go, go, go, go)\nThis is my show\nNeed you baby, like I breathe you, baby\nNeed you baby, more, more, more, more\nNeed you baby, like I breathe you, baby\nFuckin\' need you baby, more, more, more, more\nLay me down tonight in my linen and curls\nLay me down tonight, I\'m your favorite girl\nI fucked my way up to the top\nThis is my show\nI fucked my way up to the top\nGo, baby, go (go, go, go, go, go)\nThis is my show (go, go, go, go, go)\nThis is my show\nNeed you baby, like I breathe you, baby\nI need you baby, more, more, more, more\nNeed you baby, like I breathe you, baby, ah" },
                    { trackName: "Old Money", lyrics: "Blue hydrangea, cold cash divine\nCashmere, cologne, and white sunshine\nRed racing cars, Sunset and Vine\nThe kids were young and pretty\nWhere have you been?\nWhere did you go?\nThose summer nights seem long ago\nAnd so is the girl you used to call\nThe queen of New York City\nBut if you send for me, you know I\'ll come\nAnd if you call for me, you know I\'ll run\nI\'ll run to you, I\'ll run to you\nI\'ll run, run, run\nI\'ll come to you, I\'ll come to you\nI\'ll come, come, come\nOh-oh oh, oh-oh oh\nThe power of youth is on my mind\nSunsets, small town, I\'m out of time\nWill you still love me when I shine\nFrom words but not from beauty\nMy father\'s love was always strong\nMy mother\'s glamour lives on and on\nYet still inside, I felt alone\nFor reasons unknown to me\nBut if you send for me, you know I\'ll come\nAnd if you call for me, you know I\'ll run\nI\'ll run to you, I\'ll run to you\nI\'ll run, run, run\nI\'ll come to you, I\'ll come to you\nI\'ll come, come, come\nOh-oh oh, oh-oh oh\nAnd if you call I\'ll run, run, run\nIf you change your mind, I\'ll come, come, come\nOh-oh oh, ah-ah ah\nBlue hydrangea, cold cash divine\nCashmere, cologne and hot sunshine\nRed racing cars, Sunset and Vine\nAnd we were young and pretty" },
                    { trackName: "The Other Woman", lyrics: "The other woman has time to manicure her nails\nThe other woman is perfect where her rival fails\nAnd she\'s never seen with pin curls in her hair anywhere\nThe other woman enchants her clothes with French perfume\nThe other woman keeps fresh cut flowers in each room\nAnd there are never toys that\'s scattered everywhere\nAnd when her old man comes to call\nHe finds her waiting like a lonesome queen\n\'Cause to be by her side\nIt\'s such a change from old routine\nThe other woman will always cry herself to sleep\nThe other woman will never have his love to keep\nAnd as the years go by, the other woman will spend her life alone\nAlone" },
                    { trackName: "Black Beauty", lyrics: "I paint my nails black\nI dye my hair a darker shade of brown\n\'Cause you like your women Spanish, dark, strong and proud\nI paint the sky black\nYou said if you could have your way\nYou\'d make it nighttime all today\nSo it\'d suit the mood with your soul\nOh, what can I do?\nNothing, my sparrow blue\nOh, what can I do?\nLife is beautiful, but you don\'t have a clue\nSun and ocean blue\nTheir magnificence, it don\'t make sense to you\nBlack beauty,\nBlack beauty, \nI paint the house black\nMy wedding dress black leather too\nYou have no room for light, love is lost on you\nI keep my lips red\nTo seem like cherries in the spring\nDarling, you can\'t let everything seem so dark blue\nBut oh, what can I do\nTo turn you on or get through you?\nOh, what can I do?\nLife is beautiful, but you don\'t have a clue\nSun and ocean blue\nTheir magnificence, it don\'t make sense to you\nBlack beauty,\nBlack beauty,\nBlack beauty,\nOh, what can I do?\nLife is beautiful, but you don\'t have a clue\nSun and ocean blue\nTheir magnificence, it don\'t make sense to you\nBlack beauty,\nBlack beauty," },
                    { trackName: "Guns And Roses", lyrics: "Heavy metal love of mine\nI should have learned to let you stay\nYou didn\'t want me all the time\nBut you were worth it anyway\n\'Cause you were so much better\nThan the rest of them\nOut of all the others\nYou were the honest man\nHe loved guns and roses\nGuns and roses\nHe loved guns and roses\nHe loved guns\nAnd roses, roses, roses\nMotorcycle love divine\nI should have learned to let you play\nI wasn\'t the marrying kind\nI should have done it anyway\nWe should have left Las Vegas\nAnd then began again\nTook your bike to Detroit\nBack to the promised land\nHe loved guns and roses\nGuns and roses\nHe loved guns and roses\nHe loved guns\nAnd roses, roses, roses\nI can feel it coming in the air tonight\nSee you walking on that blue Pacific\nI can see you bathing in the summer light\nTurning tan and you look terrific\nYou got game boy, game boy\nYou got game boy, game boy\nYou got game boy, game boy\nYou got game\nHe loved guns and roses\nGuns and roses\nHe loved guns and roses\nHe loved guns\nAnd roses, roses, roses\nHe loved guns and roses (oh)\nGuns and roses (oh)\nHe loved guns and roses (oh)\nHe loved guns (oh)\nAnd roses (roses), roses (roses), roses (roses)" },
                    { trackName: "Florida Kilos", lyrics: "White lines, pretty baby, tattoos\nDon\'t know what they mean, they\'re special, just for you\nWhite lines, baking powder on the stove\nCooking up a dream, turning diamonds into snow\nI feel you, pretty baby, feel me\nTurn it up hot, loving you is free\nI like it down, like it down, way low\nBut you already know that, you already know\nCome on down to Florida, I got somethin\' for ya\nWe could see the kilos or the Keys, baby, oh yeah\nGuns in the summertime, chic-a-Cherry Cola lime\nPrison isn\'t nothing to me, if you\'ll be by my side\nYayo, yayo, yayo\nAnd all the dope fiends\nYayo, yayo, yayo\nStrung in my mouth and gold hoops\nYou like your little baby like you like your drinks, cool\nWhite lines, pretty daddy, go skiing\nYou snort it like a champ, like the winter we\'re not in\nCome on down to Florida, I got somethin\' for ya\nWe could see the kilos or the Keys, baby, oh yeah\nGuns in the summertime, chic-a-Cherry Cola lime\nPrison isn\'t nothing to me, if you\'ll be by my side\nYayo, yayo, yayo\nAnd all the dope fiends\nYayo, yayo, yayo\nWe could get high in Miami, ooh-ooh\nDance the night away\nPeople never die in Miami, ooh-ooh\nThat\'s what they all say\n(You believe me, don\'t you baby?)\nCome on down to Florida, I got somethin\' for ya\nWe could see the kilos or the Keys, baby, oh yeah\nGuns in the summertime, chic-a-Cherry Cola lime\nPrison don\'t mean nothing to me, if you\'ll be by my side\nYayo, yayo, yayo\nAll the Floridians like\nYayo, yayo, yayo\nAll the Colombians like\nYayo, yayo, yayo\nAnd all my girlfriends\nYayo, yayo, yayo\nThat\'s how we do it, like\nMm-mm, pretty baby\nWhite lines, pretty baby\nGold teeth, pretty baby\nDance the night away" },
                ]
            },
        ]
    }
]


